global using System.Net;
global using Mapster;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Onion.Api.Extensions;
global using Onion.Api.Interfaces;
global using Onion.Api.Logging;
global using Onion.Api.Middleware;